/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_hero_util_MsgDigest */

#ifndef _Included_com_example_administrator_hero_util_MsgDigest
#define _Included_com_example_administrator_hero_util_MsgDigest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_hero_util_MsgDigest
 * Method:    encryFromJni
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_hero_util_MsgDigest_encryFromJni
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_administrator_hero_util_MsgDigest
 * Method:    decryFromJni
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_hero_util_MsgDigest_decryFromJni
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
